---

    - name: Install packages needed to compile coturn server
      action: "apt pkg={{item}} state=installed"
      with_items:
       - gcc
       - make
       - autoconf
       - libevent-dev
       - libsqlite3-dev

    - name: Clone coturn from github
      git:
        repo: https://github.com/coturn/coturn.git
        dest: /usr/src/coturn
        force: yes
      register: coturn

    - name: Compile and install coturn
      command: "./configure && make && make install"
      args:
        chdir: /usr/src/coturn
      when: coturn.changed

    - name: Install turnserver config
      template:
        src: etc/turnserver.conf.j2
        dest: /etc/turnserver.conf

    - name: Install systemd unit
      template:
        src: etc/systemd/system/turnserver.service.j2
        dest: /etc/systemd/system/turnserver.service
        mode: 0644

    - name: Reload daemons
      command: systemctl daemon-reload
      when: coturn.changed

    - name: Enable turn server
      service:
        name: turnserver
        enabled: yes
        state: started

